# Generated by Django 4.2.6 on 2023-11-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_category',
            field=models.CharField(blank=True, help_text='This field helps to identify which category this payment falls under', max_length=200, null=True),
        ),
    ]
