# Generated by Django 4.2.6 on 2023-11-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_payment_payment_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="bill_image_url",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="is_expense",
            field=models.BooleanField(default=False),
        ),
    ]
