# Generated by Django 4.1.7 on 2023-04-05 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_remove_user_owner_address_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Notifications created date')),
                ('updated_date', models.DateTimeField(auto_now_add=True, verbose_name='Notifications updated date')),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('notification_type', models.CharField(choices=[('payment', 'Payment'), ('maintenance', 'Maintenance'), ('application', 'Application'), ('others', 'Others')], default='others', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
