# Generated by Django 4.2 on 2023-05-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='request',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
