# Generated by Django 4.2.1 on 2023-05-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notifications_sender_alter_notifications_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='last_read',
            field=models.DateField(blank=True, null=True, verbose_name='Notifications read date'),
        ),
    ]
