# Generated by Django 4.2.3 on 2023-08-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_list',
            name='job_type',
            field=models.CharField(choices=[('Management', 'Management'), ('Sales', 'Sales'), ('Developer', 'Developer'), ('Marketing', 'Marketing')], default='Developer', max_length=100),
        ),
    ]
