# Generated by Django 4.2.4 on 2023-09-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApplication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_application',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='job_application',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='job_application',
            name='question3',
        ),
        migrations.AddField(
            model_name='job_application',
            name='questions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
