# Generated by Django 4.2.4 on 2023-09-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApplication', '0003_job_list_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_application',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
