# Generated by Django 4.2.4 on 2023-09-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApplication', '0004_alter_job_application_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_application',
            name='photo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
