# Generated by Django 4.1.7 on 2023-04-03 17:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_user_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='media/Default_user.png', upload_to='images/')),
                ('house_number', models.CharField(max_length=20, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Building created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Building Updated date')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='building.address')),
            ],
        ),
        migrations.CreateModel(
            name='building_photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=10)),
                ('criteria', models.CharField(choices=[('F', 'Fully Furnished'), ('S', 'Semi Furnished'), ('N', 'Not Furnished')], default='F', max_length=1)),
                ('appliences', models.CharField(blank=True, max_length=100)),
                ('rent_amount', models.CharField(max_length=10)),
                ('advance', models.CharField(blank=True, max_length=10, null=True)),
                ('room_type', models.CharField(choices=[('3', '3BHK'), ('2', '2BHK'), ('1', '1BHK'), ('S', 'Studio'), ('H', 'House'), ('A', 'Appartment'), ('O', 'Others')], default='H', max_length=1)),
                ('rent_period_start', models.DateField(verbose_name='rent period start')),
                ('rent_period_end', models.DateField(verbose_name='rent period end')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Room created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Room Updated date')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('floor', models.CharField(blank=True, max_length=100, null=True)),
                ('max_capacity', models.CharField(blank=True, max_length=2, null=True)),
                ('bathroom_count', models.CharField(blank=True, max_length=2, null=True)),
                ('kitchen_count', models.CharField(blank=True, max_length=2, null=True)),
                ('is_parking_available', models.BooleanField(default=True)),
                ('additional_photo', models.ManyToManyField(blank=True, to='building.documents')),
                ('building', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='building.building')),
                ('renter', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='documents',
            field=models.ManyToManyField(blank=True, to='building.documents'),
        ),
        migrations.AddField(
            model_name='building',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
