# Generated by Django 4.1.7 on 2023-04-04 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_owner'),
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.address'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
