# Generated by Django 4.1.7 on 2023-04-04 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_owner_address_created_date_and_more'),
        ('building', '0002_alter_building_address_delete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('R', 'Rejected')], default='P', max_length=1)),
                ('text', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Request created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Request Updated date')),
                ('accepted', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_requests', to='user.user')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='building.room')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='user.user')),
            ],
        ),
    ]
