# Generated by Django 4.2.6 on 2023-10-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="building",
            name="photo",
        ),
        migrations.AlterField(
            model_name="room",
            name="rent_payment_interval",
            field=models.IntegerField(
                blank=True,
                help_text="No of days a renter can have before the payment is due",
                null=True,
            ),
        ),
    ]
