# Generated by Django 4.2.6 on 2023-10-17 17:55

import building.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0003_remove_building_photo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="area",
            new_name="area_in_square_feet",
        ),
        migrations.RemoveField(
            model_name="building",
            name="documents",
        ),
        migrations.RemoveField(
            model_name="room",
            name="additional_photo",
        ),
        migrations.RemoveField(
            model_name="room",
            name="appliances",
        ),
        migrations.RemoveField(
            model_name="room",
            name="is_parking_available",
        ),
        migrations.RemoveField(
            model_name="room",
            name="kitchen_count",
        ),
        migrations.RemoveField(
            model_name="room",
            name="max_capacity",
        ),
        migrations.AddField(
            model_name="room",
            name="amenities",
            field=models.JSONField(default=building.models.Room.default_amenities),
        ),
        migrations.AddField(
            model_name="room",
            name="bedroom_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="building_type",
            field=models.CharField(
                choices=[
                    ("House", "House"),
                    ("Apartments", "Apartments"),
                    ("Others", "Others"),
                ],
                db_column="building_type",
                default="House",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="bathroom_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="floor",
            field=models.CharField(
                blank=True,
                help_text="Value will be no.of floors if building type is house else room is in which floor.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="garage_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("3BHK", "3BHK"),
                    ("2BHK", "2BHK"),
                    ("1BHK", "1BHK"),
                    ("business", "business"),
                    ("Studio", "Studio"),
                    ("Others", "Others"),
                ],
                db_column="room_type",
                default="Studio",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="Documents",
        ),
    ]
