# Generated by Django 4.1.7 on 2023-04-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='building_photos',
        ),
    ]
