# Generated by Django 4.2.6 on 2023-10-21 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0004_rename_area_room_area_in_square_feet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_photo_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_photo_Url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=350, null=True)),
                ('latest_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('meter_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bill_image_url', models.URLField(blank=True, max_length=300, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='building.room')),
            ],
        ),
    ]
