# Generated by Django 4.2 on 2023-05-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0004_alter_request_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('3BHK', '3BHK'), ('2BHK', '2BHK'), ('1BHK', '1BHK'), ('Studio', 'Studio'), ('House', 'House'), ('Appartment', 'Appartment'), ('Others', 'Others')], db_column='room_type', default='House', max_length=10),
        ),
    ]
