# Generated by Django 4.2 on 2023-05-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0005_alter_room_room_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='appliences',
            new_name='appliances',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('3BHK', '3BHK'), ('2BHK', '2BHK'), ('1BHK', '1BHK'), ('Studio', 'Studio'), ('House', 'House'), ('Apartment', 'Apartment'), ('Others', 'Others')], db_column='room_type', default='House', max_length=10),
        ),
    ]
