# Generated by Django 4.2 on 2023-05-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0006_rename_appliences_room_appliances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='building_type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Others', 'Others')], db_column='building_type', default='House', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('3BHK', '3BHK'), ('2BHK', '2BHK'), ('1BHK', '1BHK'), ('Studio', 'Studio'), ('Others', 'Others')], db_column='room_type', default='Studio', max_length=10),
        ),
    ]
