# Generated by Django 4.2.6 on 2023-11-20 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("building", "0007_lease"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="renter",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lease_renter",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lease",
            unique_together={("room", "renter")},
        ),
    ]
