# Generated by Django 4.2 on 2023-05-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0008_remove_room_building_type_building_building_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='building_document_Url',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='building_photo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
