# Generated by Django 4.2.6 on 2024-09-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0009_remove_lease_rent_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lease',
            name='tenant_acknowledge',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Rejected', 'Rejected'), ('Upcoming', 'Upcoming'), ('Current', 'Current'), ('Expiring Soon', 'Expiring Soon'), ('Expired', 'Expired')], default='Processing', max_length=15, null=True),
        ),
    ]
