# Generated by Django 4.2 on 2023-05-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0009_building_building_document_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_document_Url',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_photo_Url',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
