# Generated by Django 4.2.2 on 2023-06-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0011_alter_room_room_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='garage_count',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='bathroom_count',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='kitchen_count',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
