# Generated by Django 4.2.2 on 2023-07-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0012_room_garage_count_alter_room_bathroom_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_photo_Url',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
