# Generated by Django 4.2.5 on 2023-09-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0015_alter_room_renter'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rent_payment_date',
            field=models.DateField(blank=True, help_text='Date from which the payment of a month start', null=True, verbose_name='rent payment date'),
        ),
        migrations.AddField(
            model_name='room',
            name='rent_payment_interval',
            field=models.IntegerField(blank=True, help_text='No of days a renter can have before the payment is due', max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='rent_period_end',
            field=models.DateField(help_text='Rent period contract end date', verbose_name='rent period end'),
        ),
        migrations.AlterField(
            model_name='room',
            name='rent_period_start',
            field=models.DateField(help_text='Rent period contract start date', verbose_name='rent period start'),
        ),
    ]
