# Generated by Django 4.2 on 2023-05-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_aadhar_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(choices=[('+1', 'United States'), ('+91', 'India'), ('+86', 'China'), ('+44', 'United Kingdom'), ('+49', 'Germany'), ('+966', 'Saudi Arabia')], db_column='building_type', default='India', max_length=6),
        ),
    ]
