# Generated by Django 4.1.7 on 2023-04-04 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='owner',
        ),
        migrations.AddField(
            model_name='address',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Address created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Address Updated date'),
        ),
        migrations.AddField(
            model_name='documents',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Document created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documents',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Document Updated date'),
        ),
    ]
