# Generated by Django 4.2 on 2023-05-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aadhar',
        ),
        migrations.AddField(
            model_name='user',
            name='identification_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='identification_type',
            field=models.CharField(blank=True, choices=[('Aadhar', 'Aadhar'), ('Driving_Licence', 'Driving_Licence')], db_column='identification_type', default='Aadhar', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_document_Url',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_photo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(choices=[('code_1', 'United States'), ('code_91', 'India'), ('code_86', 'China'), ('code_44', 'United Kingdom'), ('code_49', 'Germany'), ('code_966', 'Saudi Arabia')], db_column='country_code', default='India', max_length=10),
        ),
    ]
