# Generated by Django 4.2.5 on 2023-09-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_aadhar_user_identification_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether the user email is verified or not', verbose_name='Email Verified'),
        ),
    ]
