# Generated by Django 4.1.7 on 2023-04-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhar',
            field=models.CharField(max_length=12),
        ),
    ]
