# Generated by Django 4.2.5 on 2023-09-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verified',
            new_name='is_verified_email',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified_phone_number',
            field=models.BooleanField(default=False, help_text='Designates whether the user phone number is verified or not', verbose_name='Phone Number Verified'),
        ),
    ]
