# Generated by Django 4.1.7 on 2023-04-21 12:42

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.UserAccountManager()),
            ],
        ),
    ]
