# Generated by Django 4.1.7 on 2023-04-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_aadhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='media/Default_user.png', upload_to='media/'),
        ),
    ]
